name: Lint, Test and Deploy to Vercel

on:
  push:
    branches:
      - master

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Claude CLI
        run: npm install -g @anthropic-ai/claude-cli

      - name: Run Claude Linter
        env:
          CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
        run: |
          git diff $(git rev-parse HEAD^)..HEAD || true | claude -p 'you are a linter. please review the following code changes for typos. report the filename and line number on one line, and a description of the issue on the second line. do not return any other text.'

  deploy:
    needs: lint_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          production: true

